name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: android/app/

    steps:
    # SDL submodule
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build with Gradle
      run: android/gradlew build
    - uses: actions/upload-artifact@v1
      with:
         name: release-apk
         path: android/app/build/outputs/apk/release/app-release-unsigned.apk
