name: Windows x64 C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup MSYS2 and install packages
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-make
          mingw-w64-x86_64-gcc
          mingw-w64-clang-x86_64-SDL2
          mingw-w64-clang-x86_64-SDL2_mixer
          mingw-w64-clang-x86_64-SDL2_image
          mingw-w64-clang-x86_64-libzip
    
    - name: make
      run: make -C mingw/x86_64/
